// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
)

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id=$1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, original_url, short_name, short_url, created_at
FROM links
WHERE id=$1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getListLinks = `-- name: GetListLinks :many
SELECT id, original_url, short_name, short_url, created_at
FROM links
ORDER BY id
`

func (q *Queries) GetListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getListLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newLink = `-- name: NewLink :one
INSERT INTO links (original_url, short_name, short_url)
VALUES ($1, $2, $3)
RETURNING id, original_url, short_name, short_url, created_at
`

type NewLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) NewLink(ctx context.Context, arg NewLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, newLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateLinkByID = `-- name: UpdateLinkByID :one
UPDATE links
SET original_url=$2,
    short_name=$3,
    short_url=$4
WHERE id=$1
    RETURNING id, original_url, short_name, short_url, created_at
`

type UpdateLinkByIDParams struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) UpdateLinkByID(ctx context.Context, arg UpdateLinkByIDParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLinkByID,
		arg.ID,
		arg.OriginalUrl,
		arg.ShortName,
		arg.ShortUrl,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}
