// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links_visits.sql

package db

import (
	"context"
)

const countVisits = `-- name: CountVisits :one
SELECT COUNT(*)
FROM link_visits
`

func (q *Queries) CountVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVisit = `-- name: CreateVisit :one
INSERT INTO link_visits(link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, link_id, created_at, ip, user_agent, referer, status
`

type CreateVisitParams struct {
	LinkID    int32  `json:"link_id"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	Referer   string `json:"referer"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, createVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
	)
	return i, err
}

const getListVisits = `-- name: GetListVisits :many
SELECT id, link_id, created_at, ip, user_agent, referer, status
FROM link_visits
ORDER BY id LIMIT $1 OFFSET $2
`

type GetListVisitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetListVisits(ctx context.Context, arg GetListVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, getListVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
